[package]
name = "mcsrvstatus"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termion = "4.0.3"
tui = "0.19.0"
